import os


SCREENING_MODE = os.getenv(
    "SCREENING_MODE",
    "auto",
).lower()

OPENAI_MODEL = os.getenv(
    "OPENAI_MODEL",
    "gpt-5-mini",
)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

AI_PROJECT_MAX = 40
PYTHON_BACKEND_MAX = 30
CLOUD_FULLSTACK_MAX = 15
GITHUB_MAX = 10
ENGINEERING_DEPTH_MAX = 5
MAX_SHALLOW_PROJECT_PENALTY = 15